service: JoongonaraToSlack

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-2
  profile: ifa
  memorySize: 512
  timeout: 60
  iamRoleStatements: # permissions for all of your functions can be set here
  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"

package:
  exclude:
    - ./**
  include:
    - ./main.py
    - ./migrate.py
    - ./models.py
    - ./slack_bot.py
    - ./crawling.py
    - ./bin/phantomjs

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  main:
    handler: main.handler
    events:
      - schedule: rate(3 minutes)
    environment:
      SLACK_CHANNEL: ${env:SLACK_CHANNEL}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
